### ISSUE TITLE
Update Magnolia dependencies to current version

### ISSUE THREAD

**Issue by wolf-bubenik** [IBM/magkit-test#8]
- min: 6.2.19
- max: latest (which one to use?)
- Update all dependencies according to Magnolia version
- Make tests run with new magnolia-core test-jar

**Comment by serialcool** [comment]
I think 6.2.18 should be good enough for downwards compatibility.

**Comment by wolf-bubenik** [comment]
Yes, this would than be the minimal compatible magnolia version

**Comment by wolf-bubenik** [comment]
done by @payamST
